# Generated by Django 2.0.4 on 2018-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=60)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
            ],
        ),
    ]
