# Generated by Django 2.0.4 on 2018-04-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
